apiVersion: v1
kind: Service
metadata:
  name: {{ required "Common name is needed" .Values.commonName }}-postgres-service
  namespace: {{ printf "%s-%s" .Values.commonName .Values.envSuffix }}  
  labels:
    app: {{ printf "%s-%s" .Values.commonName .Values.envSuffix }}-postgres
spec:
  type: NodePort
  selector:
    app: {{ printf "%s-%s" .Values.commonName .Values.envSuffix }}-postgres
  ports:
   - port: 5432