apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ printf "%s-%s" .Values.commonName .Values.envSuffix }}
data:
  POSTGRES_DB: {{ .Values.db_user }}
  POSTGRES_USER: {{ .Values.db_user }}
  POSTGRES_PASSWORD: {{ .Values.db_pwd }}
